kind: pipline
name: Winsper-Consumer

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package consumer completed 🙂🙂🙂"

- name: upload
  image: appleboy/drone-scp
  settings:
    host: 47.103.0.246
    username: root
    password:
      from_secret: yjy_password
    rm: true
    target: /Winsper/consumer
    source:
    - target/consumer-0.0.1-SNAPSHOT.jar
    - Dockerfile

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 47.103.0.246
    username: root
    password:
      from_secret: yjy_password
    script:
    - cd /Winsper/consumer/target
    - cp ../Dockerfile .
    - docker build -t winsper-consumer .
    - docker rm -f winsper-consumer-c
    - docker run -d --name winsper-consumer-c -p 7110:7110 winsper-consumer

volumes:
- name: dependency
  host:
    path: /root/.m2